baseURL = "https://deniskyashif.com/"
languageCode = "en-us"
title = "Blog â€¢ Denis Kyashif"
theme = "tale"
disqusShortname = "deniskyashif"
PygmentsCodeFences = true
PygmentsStyle = "emacs"
googleAnalytics = "UA-133185625-1"

[author]
  name = "Denis Kyashif"
  homepage = "https://deniskyashif.com"

[params]
  description = "My personal blog about software."
  og_image = "/images/site-feature-image.png"

[taxonomies]
  series = "series"

[permalinks]
  posts = "/:year/:month/:day/:title/"